services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - waste-dashboard

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - waste-dashboard

networks:
  waste-dashboard:
    driver: bridge

volumes:
  backend_node_modules:
